version: '2.3'

services:
  face_recognition:
    image: face_recognition
    container_name: face_recognition
    working_dir: /face_recognition/examples
    build:
      context: .
      # dockerfile: Dockerfile.gpu 
    command: python3 -u starter.py
    volumes:
      - ./:/face_recognition
    # runtime: nvidia
